version: '3'
services:
  your_app_name:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEVICE_IP=192.168.1.15
      - CONFIG_PATH=device.json
      - DUMP_PATH=acDump.json
      - MQTT_BROKER=192.168.1.51
      - MQTT_PORT=1883
      - MQTT_TOPIC=aircons/office/info_dump
      - MQTT_USERNAME=user1
      - MQTT_PASSWORD=Password1
      - LOG_LEVEL=DEBUG  # Set log level here (e.g., DEBUG, INFO, ERROR)
    restart: always  # Restart the container automatically if it exits
